#!/bin/sh
# OpenClaw init.d service script

### BEGIN INIT INFO
# Provides:          openclaw
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       OpenClaw Agentic Agent
### END INIT INFO

DAEMON=/usr/local/bin/openclaw
NAME=openclaw
PIDFILE=/var/run/openclaw.pid

case "$1" in
    start)
        echo "Starting $NAME..."
        $DAEMON &
        echo $! > $PIDFILE
        echo "$NAME started."
        ;;
    stop)
        echo "Stopping $NAME..."
        if [ -f $PIDFILE ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f $PIDFILE
        fi
        echo "$NAME stopped."
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
            echo "$NAME is running (PID $(cat $PIDFILE))"
        else
            echo "$NAME is not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
