"""
OpenClaw Task Executor

Executes planned tasks by interacting with hardware and system interfaces.
"""

import os
import subprocess
import logging
from typing import Any

from openclaw.agent.planner import Task, TaskType, TaskStatus
from openclaw.agent.memory import AgentMemory


class TaskExecutor:
    """
    Executes tasks generated by the planner.

    Maps task types to execution handlers and manages hardware interaction
    during task execution.
    """

    def __init__(self, hardware: dict, memory: AgentMemory, logger: logging.Logger):
        self.hardware = hardware
        self.memory = memory
        self.log = logger.getChild("executor")

        # Map task types to handlers
        self._handlers = {
            TaskType.SYSTEM_CHECK: self._handle_system_check,
            TaskType.HARDWARE_PROBE: self._handle_hardware_probe,
            TaskType.SECURITY_SCAN: self._handle_security_scan,
            TaskType.USER_COMMAND: self._handle_user_command,
            TaskType.MAINTENANCE: self._handle_maintenance,
            TaskType.OBSERVATION: self._handle_observation,
            TaskType.GOAL_STEP: self._handle_goal_step,
            TaskType.CLOUD_PROBE: self._handle_cloud_probe,
        }

    def execute(self, task: Task) -> dict:
        """Execute a task and return results."""
        handler = self._handlers.get(task.task_type)
        if handler is None:
            return {
                "success": False,
                "error": f"No handler for task type: {task.task_type}",
            }

        try:
            result = handler(task)
            task.status = TaskStatus.COMPLETED
            return result
        except Exception as e:
            self.log.error("Task execution error: %s", e)
            task.status = TaskStatus.FAILED
            return {"success": False, "error": str(e)}

    def _handle_system_check(self, task: Task) -> dict:
        """Check system resources and health."""
        info = {}

        # CPU info
        try:
            with open("/proc/cpuinfo", "r") as f:
                cpuinfo = f.read()
            cpu_count = cpuinfo.count("processor\t:")
            model = ""
            for line in cpuinfo.split("\n"):
                if line.startswith("model name"):
                    model = line.split(":", 1)[1].strip()
                    break
            info["cpu"] = {"cores": cpu_count, "model": model}
        except FileNotFoundError:
            info["cpu"] = {"error": "/proc/cpuinfo not available"}

        # Memory info
        if self.hardware.get("memory"):
            info["memory"] = self.hardware["memory"].get_stats()
        else:
            try:
                with open("/proc/meminfo", "r") as f:
                    meminfo = f.read()
                info["memory"] = {"raw": meminfo[:500]}
            except FileNotFoundError:
                info["memory"] = {"error": "not available"}

        # Uptime
        try:
            with open("/proc/uptime", "r") as f:
                uptime = float(f.read().split()[0])
            info["uptime_seconds"] = uptime
        except (FileNotFoundError, ValueError):
            pass

        # Load average
        try:
            with open("/proc/loadavg", "r") as f:
                info["loadavg"] = f.read().strip()
        except FileNotFoundError:
            pass

        self.memory.store(category="system_check", data=info)
        return {"success": True, "output": info}

    def _handle_hardware_probe(self, task: Task) -> dict:
        """Probe and enumerate hardware devices."""
        devices = {}

        # Display
        if self.hardware.get("display"):
            try:
                devices["display"] = self.hardware["display"].get_state()
            except Exception as e:
                devices["display"] = {"error": str(e)}

        # Input devices
        if self.hardware.get("input"):
            try:
                devices["input"] = self.hardware["input"].list_devices()
            except Exception as e:
                devices["input"] = {"error": str(e)}

        # Storage
        if self.hardware.get("storage"):
            try:
                devices["storage"] = self.hardware["storage"].get_devices()
            except Exception as e:
                devices["storage"] = {"error": str(e)}

        # PCI devices (if lspci available)
        try:
            result = subprocess.run(
                ["lspci", "-mm"],
                capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                devices["pci"] = result.stdout[:2000]
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

        # USB devices
        try:
            result = subprocess.run(
                ["lsusb"],
                capture_output=True, text=True, timeout=5
            )
            if result.returncode == 0:
                devices["usb"] = result.stdout[:1000]
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

        self.memory.store(category="hardware_probe", data=devices)
        return {"success": True, "output": devices}

    def _handle_security_scan(self, task: Task) -> dict:
        """Run a security scan."""
        from openclaw.security.scanner import SecurityScanner
        scanner = SecurityScanner()
        report = scanner.full_scan()
        self.memory.store(category="security_scan", data=report)
        return {"success": True, "output": report}

    def _handle_user_command(self, task: Task) -> dict:
        """Handle a user-initiated command via input devices."""
        event = task.metadata.get("event", {})
        self.log.info("Processing user input event: %s", event)

        # Store the event for the UI to process
        self.memory.store(
            category="user_input",
            data={"event": event, "processed": True},
        )
        return {"success": True, "output": {"event_processed": True}}

    def _handle_maintenance(self, task: Task) -> dict:
        """Handle system maintenance tasks."""
        description = task.description.lower()

        if "memory" in description:
            # Log memory state
            if self.hardware.get("memory"):
                stats = self.hardware["memory"].get_stats()
                self.log.warning("Memory maintenance: %s", stats)
                return {"success": True, "output": stats}

        if "storage" in description:
            # Check storage health
            if self.hardware.get("storage"):
                devices = self.hardware["storage"].get_devices()
                return {"success": True, "output": devices}

        return {"success": True, "output": {"action": "logged"}}

    def _handle_observation(self, task: Task) -> dict:
        """Passive observation of system state."""
        state = {}
        for name, hw in self.hardware.items():
            if hw is not None:
                try:
                    state[name] = hw.get_state() if hasattr(hw, "get_state") else "active"
                except Exception:
                    state[name] = "error"
        return {"success": True, "output": state}

    def _handle_cloud_probe(self, task: Task) -> dict:
        """Ask the cloud metadata service who and where we are."""
        from openclaw.cloud.imds import IMDSClient
        imds = IMDSClient()
        info = imds.summary()
        if not info:
            info = {"provider": "none", "available": False}
        else:
            info["available"] = True
        self.memory.store(category="cloud_probe", data=info)
        return {"success": True, "output": info}

    def _handle_goal_step(self, task: Task) -> dict:
        """Execute a step toward a goal."""
        goal = task.metadata.get("goal", "unknown")
        self.log.info("Working toward goal: %s", goal)

        # Store progress
        self.memory.store(
            category="goal_progress",
            data={"goal": goal, "step": task.description},
        )
        return {"success": True, "output": {"goal": goal, "progressed": True}}
